  CREATE SEQUENCE  KSS_ASSIGNMENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 NOORDER  NOCYCLE ;

  CREATE TABLE KSS_ASSIGNMENT 
   (
    ASSIGNMENT_ID NUMBER(20,0) NOT NULL ENABLE, 
	ASSIGNMENT_NAME VARCHAR2(500), 
	ASSIGNMENT_DESC VARCHAR2(500), 
	OWNER VARCHAR2(256), 
	CREATED_AT DATE, 	
	STATUS VARCHAR2(30), 
	CONSTRAINT PK_KSS_ASSIGNMENT PRIMARY KEY (ASSIGNMENT_ID)
   )  ;
   
   
  CREATE TABLE KSS_ASSIGNMENT_ITEM
   (
    ASSIGNMENT_ID NUMBER(20,0) NOT NULL ENABLE, 
	ITEM_ID NUMBER(20,0) NOT NULL ENABLE, 
	ITEM_DESC VARCHAR2(4000), 
	WEIGHTAGE NUMBER,
	ITEM_TYPE VARCHAR2(256),
	CREATED_AT DATE, 	
	STATUS VARCHAR2(30), 
	CONSTRAINT PK_KSS_ASSIGNMENT_ITEM PRIMARY KEY (ASSIGNMENT_ID, ITEM_ID)
   ) ;   
   
   
  CREATE TABLE KSS_ASSIGNMENT_ITEM_CHOICE
   (
    ASSIGNMENT_ID NUMBER(20,0) NOT NULL ENABLE,
	ITEM_ID NUMBER(20,0) NOT NULL ENABLE, 
	CHOICE_ID NUMBER(20,0) NOT NULL ENABLE,	
	CHOICE_VALUE NUMBER,
	IS_CORRECT VARCHAR2(10),
	CONSTRAINT PK_KSS_ASSIGNMENT_ITEM_CHOICE PRIMARY KEY (ASSIGNMENT_ID, ITEM_ID, CHOICE_ID)
   )  ;     
   
   
  CREATE TABLE KSS_USER
   (
    USER_ID VARCHAR2(256) NOT NULL ENABLE,
	USER_PASSWORD VARCHAR2(256) DEFAULT 'Welcome1' NOT NULL ENABLE,
	USER_ROLE VARCHAR2(100),
	CREATED_AT DATE, 	
	STATUS VARCHAR2(30), 
	CONSTRAINT PK_KSS_USER PRIMARY KEY (USER_ID)
   )  ;     
   
   
  CREATE TABLE KSS_USER_ASSIGNMENT
   (
    USER_ID VARCHAR2(256) NOT NULL ENABLE,
    ASSIGNMENT_ID NUMBER(20,0) NOT NULL ENABLE,
	MODIFIED_AT DATE, 
	SCORE NUMBER,
	COMMENTS VARCHAR2(4000),
	STATUS VARCHAR2(30), 
	CONSTRAINT PK_KSS_USER_ASSIGNMENT PRIMARY KEY (USER_ID, ASSIGNMENT_ID)
   )  ;    
   

  CREATE TABLE KSS_USER_ASSIGNMENT_ITEM
   (
    USER_ID VARCHAR2(256) NOT NULL ENABLE,
    ASSIGNMENT_ID NUMBER(20,0) NOT NULL ENABLE, 
	ITEM_ID NUMBER(20,0) NOT NULL ENABLE, 
	USER_INPUT VARCHAR2(1000), 
	SCORE NUMBER,
	COMMENTS VARCHAR2(4000),
	STATUS VARCHAR2(30), 
	CONSTRAINT PK_KSS_USER_ASSIGNMENT_ITEM PRIMARY KEY (USER_ID, ASSIGNMENT_ID, ITEM_ID)
   )  ;   
     
   
   
   